pipeline {
    agent any

    tools {
        jdk 'JAVA_HOME'
        maven 'MAVEN_HOME'
    }

    environment {
        TEST_REPO = 'https://github.com/empresarialmaia/matins'
        TEST_DIR = 'matins'
    }

    stages {
        stage('Checkout Code') {
            steps {
                echo 'Clonando os repositórios'
                dir("${TEST_DIR}") {
                    git branch: 'main', url: "${TEST_REPO}"
                }
            }
        }

        stage('Build Application') {
            steps {
                echo 'Construindo a aplicação'
                dir("${TEST_DIR}") {
                    bat 'mvn clean install'
                }
            }
        }

        stage('Executar os Testes') {
            steps {
                echo 'Executando os testes'
                dir("${TEST_DIR}") {
                    bat 'mvn test'
                }
            }
        }

        stage('Build Artefato') {
            steps {
                echo 'Criando o artefato final'
                bat 'mvn clean package -DskipTests=true'
            }
        }

        stage('Deploy') {
            steps {
                script {
                    echo 'Iniciando o deploy...'
                    // Caminho do artefato gerado pelo Maven
                    def artefato = "${TEST_DIR}\\target\\projetoMantis-0.0.1-SNAPSHOT.jar"  // Corrigido o caminho do artefato
                    // Caminho do destino para o deploy
                    def destino = "C:\\Users\\hercu\\eclipse-workspace\\mantis\\deploy\\target\\"
                    
                    // Criando o diretório de destino, caso não exista
                    bat "if not exist ${destino} mkdir ${destino}"
                    
                    // Copiando o artefato para o destino
                    if (fileExists(artefato)) {
                        bat "copy \"${artefato}\" \"${destino}\""
                        echo 'Deploy realizado com sucesso!'
                    } else {
                        error "Artefato não encontrado: ${artefato}"
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Gerando status report'
            script {
                if (currentBuild.result == 'SUCCESS') {
                    echo 'Pipeline executada com sucesso'
                } else if (currentBuild.result == 'FAILURE') {
                    echo 'EXECUÇÃO DA PIPELINE FALHOU'
                } else {
                    echo 'Pipeline com status desconhecido'
                }
            }
        }
    }
}
