pipeline {
	agent any
	stages {
	  stage('Build projeto Mantis'){
	      steps {
	          bat 'mvn clean package -DskipTests=true'	  
	  }
	}
	stage('Tests'){
	      steps {
	          bat 'mvn test'	  
	  }
	}
  }
}