pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                // Etapa de build
                echo 'Iniciando o processo de build...'
                bat 'mvn clean package -DskipTests=true'
            }
        }
        stage('Tests') {
            steps {
                // Executa os testes
                echo 'Executando testes...'
                bat 'mvn test -Dtest=Executa'
            }
            post {
                always {
                    // Publica os resultados dos testes no formato JUnit
                    junit 'C:\\Users\\hercu\\eclipse-workspace\\mantis\\projetoMantis\\target\\surefire-reports\\TEST-*.xml' // Ajuste o caminho conforme necessário
                }
            }
        }
        stage('Deploy') {
            steps {
                echo 'Iniciando deploy...'
                bat 'mvn deploy'
            }
        }
    }
    post {
        always {
            // Limpeza ou ações finais
            echo 'Pipeline finalizado!'
        }
    }
}
